### ISSUE TITLE
Allow some insights about the contribution

### ISSUE THREAD

**Issue by BinaryCoder87** [NetWatch-team/SSH-AttackPod#5]
It would be nice to somehow be able to see some statistics, like how many attempts have been logged from how many different IPs, for example. But it's a nice-to-have, of course.

**Comment by eliphaslevy** [comment]
This needs latest code that outputs log evidence converted to JSON. Latest official docker image is outdated as of now.

```SINCE=${1:-1m} # time span
cname=netwatch_ssh-attackpod
# 2025-01-01 00:11:42,333 Reported the following JSON to the NetWatch collector: {"source_ip": 
msg_match='^[0-9 :,.A-z-]\+ collector: '

# stats:
{
echo -e "Count\tIP\tTime"
docker logs --since ${SINCE} "${cname}" 2>&1 |
        sed -n "s/${msg_match}//p" |
        jq -r '.attack_timestamp |= split("T")[0] | [.source_ip, .attack_timestamp] | @tsv ' |
        sort -V |
        uniq -c
} | column -t

# list last attempts:
{
echo -e "Timestamp\tIP\tuser\tpass"
docker logs --since ${SINCE} "${cname}" 2>&1 |
        sed -n "s/${msg_match}//p" |
        jq -r '[.attack_timestamp, .source_ip, .username, .password] | @tsv'
} | column -t

# sample:
root@hopper:~/netwatch# ./stats.sh 30s
Count  IP               Time
1      xxx.yyy.zzz.aaa  2025-01-22
root@hopper:~/netwatch# ./list.sh 30s
Timestamp                   IP          user       pass
2025-01-22T19:23:23.079327  a.b.c.d     validator  validator
2025-01-22T19:23:26.869703  z.z.z.z     root       tiep0410
2025-01-22T19:23:27.256699  z.z.z.z     root       sanja13
2025-01-22T19:23:27.600203  z.z.z.z     root       tennis
```

**Comment by KingUdo** [comment]
Hey @BinaryCoder87 
I just pushed the first version of the Community AttackPod insights here: https://community.netwatch.team/insight/
By adding your API key you can now get a few insights about the attacks you AttackPod submitted, the number of cases the AttackPod supported in creating  as well as the last attacks seen.
Would there be anything else you would like to see there?

**Comment by BinaryCoder87** [comment]
Thanks a lot! Any chance it would run on an iPhone over Chrome?

**Comment by KingUdo** [comment]
It does run on mobile as well, but is for sure not designed for this => 
Let me see how I can make the whole web page more mobile friendly!

**Comment by KingUdo** [comment]
It did take a while, but we now have a community API [https://community-api.netwatch.team/](https://community-api.netwatch.team/) that allows you to query data provided by your sensor much better than the old community insights. 
Could you check if this is sufficient access you need or is there something else you would like to see?

**Comment by BinaryCoder87** [comment]
At least this one:
https://community.netwatch.team/insight/
still does not work for me. I see the last attempts but the page still failes to load the Sensor Insights.
